version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
  pre_build:
    commands:
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm install
      - cd ..
  build:
    commands:
      - echo "Building frontend..."
      - cd frontend
      - npx vite build
      - cd ..
      - echo "Creating backend .env file..."
      - echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> backend/.env
      - echo "DATABASE_URL=$DATABASE_URL" >> backend/.env
      - echo "ENV=production" >> backend/.env
  post_build:
    commands:
      - echo "Deploying frontend to S3..."
      - aws s3 sync frontend/dist s3://$S3_BUCKET_NAME/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - backend/**/*
    - scripts/**/*
    - appspec.yml